apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meta-sikademo
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: meta/sikademo
    repoURL: https://github.com/ondrejsika/argocd-apps-devopslive.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
