apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: www-example
  namespace: argocd
spec:
  destination:
    namespace: www
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/hello-world
    helm:
      releaseName: hello-world
      values: |
        host: k8s.sikademo.com
        image: sikalabs/hello-world-server:ondrejsika
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
