apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sikademo-system-ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.0.13
    helm:
      releaseName: ingress-nginx
      # https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
      values: |
        controller:
          service:
            type: ClusterIP
          ingressClassResource:
            default: true
          kind: DaemonSet
          hostPort:
            enabled: true
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
