apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devopslive
  namespace: argocd
spec:
  destination:
    namespace: devopslive
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/hello-world
    helm:
      releaseName: devopslive
      values: |
        host: devopslive.k8s.sikademo.com
        image: registry.sikalabs.com/examples/demo:94999260-master-5888
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
